// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cusiybooebbkvpduretj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1c2l5Ym9vZWJia3ZwZHVyZXRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMTM0NzEsImV4cCI6MjA1MTU4OTQ3MX0.TN8JFxDiMvxQkTLHM6F8jrNbM8jgFf4JwuKvcsppthI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);